<a href="https://colab.research.google.com/github/lukystrikeibg/python/blob/master/manipulaci%C3%B3n_de_datos_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
10+3

13

In [ ]:
2*3

6

In [ ]:
import numpy as np
np.array([1,2,3,4,5])# vector

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4,5])+10

array([11, 12, 13, 14, 15])

In [ ]:
np.array([10,8,5,0])*np.array([0,1,6,12])

array([ 0,  8, 30,  0])

indexacion y seleccion de datos

In [ ]:
import pandas as pd

In [ ]:
#series
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
sr=pd.Series([10,9,8,7,6])

sr.values

array([10,  9,  8,  7,  6])

In [ ]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#llamar elementos
sr[3]

7

In [ ]:
pd.Series([10,8,5,0])-pd.Series([0,1,6,12])

0    10
1     7
2    -1
3   -12
dtype: int64

In [ ]:
# dicionario
dict_data ={'co':100, 'Mx':200, 'Ar':300 }
dict_data

{'Ar': 300, 'Mx': 200, 'co': 100}

In [ ]:
dict_data.keys()

dict_keys(['co', 'Mx', 'Ar'])

In [ ]:
dict_data ['Mx']

200

Data frame



In [ ]:
pd.__version__

'1.1.5'

In [ ]:
dict_dato={'CH':[100,800,200],'CO':[100,200,300],'MX':[300,500,400]}
dict_dato

{'CH': [100, 800, 200], 'CO': [100, 200, 300], 'MX': [300, 500, 400]}

In [ ]:
df=pd.DataFrame(dict_dato)
df

,CH,CO,MX
0,100,100,300
1,800,200,500
2,200,300,400


In [ ]:
dict_data = {
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}
dict_data

{'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9.0],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'edad': [10, 9, 13, 14, 12, 11, 12],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch']}

In [ ]:
df=pd.DataFrame(dict_data,index=['ana','benito','camilo','daniel','erika','fabian','gabriela'])
df

,edad,cm,pais,genero,Q1,Q2
ana,10,115,co,M,5.0,7.0
benito,9,110,mx,F,10.0,9.0
camilo,13,130,co,F,8.0,9.0
daniel,14,155,mx,M,NaN,8.0
erika,12,125,mx,M,7.0,8.0
fabian,11,120,ch,M,8.0,8.0
gabriela,12,125,ch,F,3.0,9.0


In [ ]:
df.index

Index(['ana', 'benito', 'camilo', 'daniel', 'erika', 'fabian', 'gabriela'], dtype='object')

In [ ]:
df.values

array([[10, 115, 'co', 'M', 5.0, 7.0],
       [9, 110, 'mx', 'F', 10.0, 9.0],
       [13, 130, 'co', 'F', 8.0, 9.0],
       [14, 155, 'mx', 'M', nan, 8.0],
       [12, 125, 'mx', 'M', 7.0, 8.0],
       [11, 120, 'ch', 'M', 8.0, 8.0],
       [12, 125, 'ch', 'F', 3.0, 9.0]], dtype=object)

In [ ]:
df.['edad','cm','Q1']]

,edad,cm,Q1
ana,10,115,5.0
benito,9,110,10.0
camilo,13,130,8.0
daniel,14,155,NaN
erika,12,125,7.0
fabian,11,120,8.0
gabriela,12,125,3.0


In [ ]:
df.groupby(['genero'])['edad'].agg(np.mean)

genero
F    11.333333
M    11.750000
Name: edad, dtype: float64

Indexacón y Manejo de Archivos

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks/manipulación de datos'
!ls

/content/drive/My Drive/Colab Notebooks/manipulación de datos
'manipulación de datos .ipynb'	'Visualización de datos.ipynb'


In [ ]:
'hola {}'.format('lukas')

'hola lukas'

In [ ]:
!mkdir /content/drive/My\ Drive/Colab\ Notebooks/manipulación\ de\ datos/db

In [ ]:
df

,edad,cm,pais,genero,Q1,Q2
ana,10,115,co,M,5.0,7.0
benito,9,110,mx,F,10.0,9.0
camilo,13,130,co,F,8.0,9.0
daniel,14,155,mx,M,NaN,8.0
erika,12,125,mx,M,7.0,8.0
fabian,11,120,ch,M,8.0,8.0
gabriela,12,125,ch,F,3.0,9.0


In [ ]:
dir_pandas='/content/drive/My Drive/Colab Notebooks/manipulación de datos/db/{}'.format('test.csv')
dir_pandas

'/content/drive/My Drive/Colab Notebooks/manipulación de datos/db/test.csv'

In [ ]:
df.to_csv(dir_pandas)

In [ ]:
df_read=pd.read_csv('/content/drive/My Drive/Colab Notebooks/manipulación de datos/db/test.csv')
df_read

,Unnamed: 0,edad,cm,pais,genero,Q1,Q2
0,ana,10,115,co,M,5.0,7.0
1,benito,9,110,mx,F,10.0,9.0
2,camilo,13,130,co,F,8.0,9.0
3,daniel,14,155,mx,M,NaN,8.0
4,erika,12,125,mx,M,7.0,8.0
5,fabian,11,120,ch,M,8.0,8.0
6,gabriela,12,125,ch,F,3.0,9.0


In [ ]:
df_read=pd.read_csv('/content/drive/My Drive/Colab Notebooks/manipulación de datos/db/test.csv')
df_read

In [ ]:
print(df.query("(edad >= 12) & (cm < 130) & (Q1 > 5)")['Q2'])

erika    8.0
Name: Q2, dtype: float64
